"""Public API snapshots for the frozen sync surfaces (#875).

#875 makes one promise above all others: finishing async support must not
rename, remove, or change the signature of anything the existing sync API
already exposes. A promise nobody checks is a wish, so this renders the public
sync surface -- Rust and Python -- into checked-in text files and fails when the
rendering changes.

The snapshot is deliberately *not* a formatted-source dump. It records the
things a downstream consumer can actually break on:

* which names are exported, and from where
* the parameter list of every public callable, in order, with defaults
* whether a parameter is keyword-only

A diff here is not automatically a bug. It is a claim that needs a reason: an
addition is usually fine, a rename or a reordered parameter is a breaking
change that needs the justification #849 governs. Regenerating is one command,
so the cost of an intentional change is one reviewable diff.

Discovery is static (`ast` for Python, a scanner for the rustfmt-guaranteed
`impl` blocks), so this runs without importing the package or building the
native extension -- which matters, because a snapshot you can only take on a
machine with a working toolchain is a snapshot nobody takes.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

from ci.parity_manifest import ROOT, SURFACES, Surface

PYTHON_SNAPSHOT = ROOT / "docs" / "api_snapshot_python.txt"
RUST_SNAPSHOT = ROOT / "docs" / "api_snapshot_rust.txt"

HEADER = (
    "# Generated by `python -m ci.api_snapshot --write`. Do not edit by hand.\n"
    "# A diff here is a change to the public {language} surface. An addition is\n"
    "# usually fine; a rename, removal, or reordered parameter is a breaking\n"
    "# change and needs the justification #849 governs.\n"
)

PACKAGE_INIT = Path("src/running_process/__init__.py")


# --------------------------------------------------------------------------
# Python
# --------------------------------------------------------------------------


def _render_default(node: ast.expr | None) -> str:
    if node is None:
        return ""
    try:
        return "=" + ast.unparse(node)
    except Exception:  # pragma: no cover - unparse handles every literal we use
        return "=<expr>"


def _render_signature(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    args = node.args
    rendered: list[str] = []

    positional = list(args.posonlyargs) + list(args.args)
    padding = [None] * (len(positional) - len(args.defaults))
    for argument, default in zip(
        positional, padding + list(args.defaults), strict=True
    ):
        rendered.append(argument.arg + _render_default(default))
    if args.posonlyargs:
        rendered.insert(len(args.posonlyargs), "/")

    if args.vararg is not None:
        rendered.append("*" + args.vararg.arg)
    elif args.kwonlyargs:
        rendered.append("*")
    for argument, default in zip(args.kwonlyargs, args.kw_defaults, strict=True):
        rendered.append(argument.arg + _render_default(default))
    if args.kwarg is not None:
        rendered.append("**" + args.kwarg.arg)

    prefix = "async def " if isinstance(node, ast.AsyncFunctionDef) else "def "
    return f"{prefix}{node.name}({', '.join(rendered)})"


def _class_members(source: str, symbol: str) -> list[str]:
    tree = ast.parse(source)
    for node in tree.body:
        if not (isinstance(node, ast.ClassDef) and node.name == symbol):
            continue
        rendered = []
        for child in node.body:
            if not isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            if child.name.startswith("_") and child.name != "__init__":
                continue
            decorators = sorted(
                ast.unparse(decorator) for decorator in child.decorator_list
            )
            marker = f"[{','.join(decorators)}] " if decorators else ""
            rendered.append(f"    {marker}{_render_signature(child)}")
        return sorted(rendered)
    raise ValueError(f"no `class {symbol}` found")


def _exports() -> list[str]:
    source = (ROOT / PACKAGE_INIT).read_text(encoding="utf-8")
    names = sorted(set(re.findall(r'^\s*"(\w+)",', source, re.MULTILINE)))
    return [f"    {name}" for name in names]


def render_python() -> str:
    lines = [HEADER.format(language="Python"), "## running_process.__all__", ""]
    lines.extend(_exports())
    for surface in SURFACES:
        if surface.language != "python":
            continue
        source = (ROOT / surface.source).read_text(encoding="utf-8")
        lines.extend(["", f"## {surface.symbol}", ""])
        lines.extend(_class_members(source, surface.symbol))
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Rust
# --------------------------------------------------------------------------


def _rust_signatures(source: str, symbol: str) -> list[str]:
    marker = re.search(rf"^impl {re.escape(symbol)}\s*\{{$", source, re.MULTILINE)
    if marker is None:
        raise ValueError(f"no `impl {symbol}` block found")
    body = source[marker.end() :].splitlines()
    rendered: list[str] = []
    collecting: list[str] = []
    for line in body:
        if line == "}":
            break
        if collecting:
            collecting.append(line.strip())
        elif re.match(r"    pub\s+(?:async\s+)?(?:unsafe\s+)?fn\s+\w+", line):
            collecting = [line.strip()]
        else:
            continue
        # A signature ends at the opening brace of the body, or at `;` for a
        # trait-style declaration. Multi-line signatures are common here.
        joined = " ".join(collecting)
        if "{" in joined or joined.endswith(";"):
            signature = joined.split("{", 1)[0].strip().rstrip(";").strip()
            collapsed = re.sub(r"\s+", " ", signature)
            rendered.append(f"    {collapsed}")
            collecting = []
    return sorted(rendered)


def _rust_exports() -> list[str]:
    source = (ROOT / "crates/running-process/src/lib.rs").read_text(encoding="utf-8")
    exports = re.findall(r"^pub use ([^;]+);", source, re.MULTILINE)
    flattened: set[str] = set()
    for export in exports:
        flattened.add(re.sub(r"\s+", " ", export.strip()))
    return [f"    pub use {entry};" for entry in sorted(flattened)]


def render_rust() -> str:
    lines = [HEADER.format(language="Rust"), "## running_process re-exports", ""]
    lines.extend(_rust_exports())
    for surface in SURFACES:
        if surface.language != "rust":
            continue
        source = (ROOT / surface.source).read_text(encoding="utf-8")
        lines.extend(["", f"## {surface.symbol}", ""])
        lines.extend(_rust_signatures(source, surface.symbol))
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------


def _targets() -> list[tuple[Path, str]]:
    return [(PYTHON_SNAPSHOT, render_python()), (RUST_SNAPSHOT, render_rust())]


def check() -> list[str]:
    failures: list[str] = []
    for path, expected in _targets():
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            failures.append(
                f"{path.name} is missing; run `python -m ci.api_snapshot --write`"
            )
            continue
        if actual != expected:
            failures.append(
                f"{path.name} does not match the current public surface. If the "
                "change is intended, run `python -m ci.api_snapshot --write` and "
                "explain the diff in the PR; a rename, removal, or reordered "
                "parameter needs the justification #849 governs."
            )
    return failures


def write() -> None:
    for path, expected in _targets():
        path.write_text(expected, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the snapshots")
    args = parser.parse_args(argv)
    if args.write:
        write()
        print("api snapshot: regenerated")
        return 0
    failures = check()
    if failures:
        print("public API snapshot gate failed:")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print("public API snapshot gate passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())


# Re-exported so callers can introspect which surfaces are covered.
__all__ = ["Surface", "check", "main", "render_python", "render_rust", "write"]
