"""Sync test inventory audit for #875.

The subtlest way to break a frozen sync API is not to change it -- it is to
delete the test that would have noticed. #875 therefore asks for proof that no
sync test was removed, weakened, silently skipped, or quietly converted into an
async-only test while async support was being added.

`docs/sync_test_baseline.txt` is that proof: the name of every synchronous test
in the tree at the point the baseline was taken. This module recomputes the
inventory and fails when a baselined name is gone.

What counts as synchronous:

* Rust -- a `#[test]` function. `#[tokio::test]` is async and is excluded.
* Python -- a `test_*` function declared with `def`, not `async def`, and not
  carrying a `skip`/`skipUnless`-style decorator that would make it vacuous.

Deliberately a one-way ratchet on *removal only*. New tests are welcome and
need no baseline update; the file is regenerated only when a removal is
intended, and then the diff is the reviewable record of what went and why.

Renaming a test reads as a removal plus an addition, which is correct: the
reviewer should confirm the coverage moved rather than evaporated.
"""

from __future__ import annotations

import argparse
import ast
import re
import sys

from ci.parity_manifest import ROOT

BASELINE = ROOT / "docs" / "sync_test_baseline.txt"

HEADER = """\
# Generated by `python -m ci.sync_test_audit --write`. Do not edit by hand.
#
# Every synchronous test in the tree when this baseline was taken. The audit
# fails when one of these names disappears -- deleting the test that would
# notice a sync regression is the quietest way to cause one.
#
# Adding tests never requires an update. Regenerate only when a removal is
# intended, and say why in the PR: the diff is the record.
"""

# A skip that is unconditional, or conditional on something that is false
# everywhere, turns a test into decoration. Those are recorded separately so a
# test cannot be neutralised by decorating it rather than deleting it.
SKIP_PATTERN = re.compile(r"\b(skip|skipIf|skipUnless|xfail)\b")


def _rust_sync_tests() -> set[str]:
    names: set[str] = set()
    for path in ROOT.glob("crates/**/*.rs"):
        if "target" in path.parts:
            continue
        attributes: list[str] = []
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("#["):
                attributes.append(stripped)
                continue
            found = re.match(r"(?:async\s+)?fn\s+(\w+)", stripped)
            if found is not None and attributes:
                joined = " ".join(attributes)
                # `#[test]` only. `#[tokio::test]` and friends are async.
                if re.search(r"#\[test\]", joined) and "tokio::test" not in joined:
                    names.add(found.group(1))
            attributes = []
    return names


def _python_sync_tests() -> tuple[set[str], set[str]]:
    """Return (sync test names, names carrying a skip decorator)."""
    names: set[str] = set()
    skipped: set[str] = set()
    for path in ROOT.glob("tests/**/*.py"):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:  # pragma: no cover - pytest fails on these anyway
            continue
        _collect(tree, inherited_skip=False, names=names, skipped=skipped)
    return names, skipped


def _decorators(node: ast.ClassDef | ast.FunctionDef) -> str:
    return " ".join(ast.unparse(decorator) for decorator in node.decorator_list)


def _collect(
    scope: ast.AST, *, inherited_skip: bool, names: set[str], skipped: set[str]
) -> None:
    """Walk one scope, carrying a class-level skip down to its methods.

    A `@unittest.skipUnless(...)` on the *class* silences every test inside it,
    so counting only function decorators would report zero skips for a whole
    file that never runs.
    """
    for node in getattr(scope, "body", []):
        if isinstance(node, ast.ClassDef):
            _collect(
                node,
                inherited_skip=inherited_skip or bool(SKIP_PATTERN.search(_decorators(node))),
                names=names,
                skipped=skipped,
            )
        elif isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
            # AsyncFunctionDef is deliberately not matched here.
            names.add(node.name)
            if inherited_skip or SKIP_PATTERN.search(_decorators(node)):
                skipped.add(node.name)


def inventory() -> tuple[set[str], set[str]]:
    rust = _rust_sync_tests()
    python, skipped = _python_sync_tests()
    return rust | python, skipped


def render() -> str:
    names, skipped = inventory()
    lines = [
        HEADER,
        f"# sync tests: {len(names)}",
        f"# of those, skip-decorated: {len(skipped)}",
        "",
    ]
    lines.extend(sorted(names))
    return "\n".join(lines) + "\n"


def _baselined() -> set[str]:
    text = BASELINE.read_text(encoding="utf-8")
    return {
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.startswith("#")
    }


def check() -> list[str]:
    try:
        baselined = _baselined()
    except OSError:
        return [f"{BASELINE.name} is missing; run `python -m ci.sync_test_audit --write`"]

    present, _skipped = inventory()
    removed = sorted(baselined - present)
    if not removed:
        return []
    failures = [
        f"{len(removed)} baselined sync test(s) no longer exist. Deleting a sync "
        "test is how a sync regression goes unnoticed -- if the removal is "
        "intended, run `python -m ci.sync_test_audit --write` and say why in the "
        "PR:"
    ]
    failures.extend(f"  removed: {name}" for name in removed[:40])
    if len(removed) > 40:
        failures.append(f"  ... and {len(removed) - 40} more")
    return failures


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the baseline")
    parser.add_argument(
        "--report",
        action="store_true",
        help="print the current inventory counts without checking",
    )
    args = parser.parse_args(argv)

    if args.write:
        BASELINE.write_text(render(), encoding="utf-8")
        print("sync test audit: baseline regenerated")
        return 0
    if args.report:
        names, skipped = inventory()
        print(f"sync tests: {len(names)}")
        print(f"skip-decorated: {len(skipped)}")
        return 0

    failures = check()
    if failures:
        print("sync test audit failed:")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print("sync test audit passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
