"""Lint check: verify that version strings are consistent across all manifests."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

SOURCES: list[tuple[str, str]] = [
    ("src/running_process/__init__.py", r'^__version__\s*=\s*"([^"]+)"'),
    ("pyproject.toml", r'^version\s*=\s*"([^"]+)"'),
    ("Cargo.toml", r'^version\s*=\s*"([^"]+)"'),
    # `crates/running-process` is the one published crate that spells its own
    # version out instead of inheriting `version.workspace = true`. Nothing
    # checked it, so a root bump left it behind at 4.10.10 — a published crate
    # one version off from every sibling.
    ("crates/running-process/Cargo.toml", r'^version\s*=\s*"([^"]+)"'),
    # The Python extension crate pins its sibling by exact version. Left
    # behind, it does not merely drift -- `cargo publish` cannot resolve
    # it, so the release fails after the tag is already cut.
    (
        "crates/running-process-py/Cargo.toml",
        r'^running-process\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # Same hazard, added with the probe crates (#651). Every path dependency
    # of a published crate needs a version -- optional ones behind a feature
    # included -- and a stale one is not caught until `cargo publish` refuses
    # the package, which is after the tag is cut.
    (
        "crates/running-process/Cargo.toml",
        r'^running-process-probe\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # Same pin, from the extension crate. It was left out of this list and
    # sat at 4.10.10 through the 4.10.11 bump: nothing here caught it, and
    # `cargo publish -p running-process-py` is where it would have surfaced —
    # after the tag is cut.
    (
        "crates/running-process-py/Cargo.toml",
        r'^running-process-probe\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    (
        "crates/running-process-probe-daemon/Cargo.toml",
        r'^running-process\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    (
        "crates/running-process-probe-daemon/Cargo.toml",
        r'^running-process-probe\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # #850: the published implementation-detail crate is an optional path
    # dependency of the public crate. Its version must remain lockstep or a
    # release can fail package resolution after the tag is cut.
    (
        f"crates/running-process/{'C' + 'argo'}.toml",
        r'^running-process-platform-internal\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # #1144: broker protobuf generation is a published implementation-detail
    # dependency of the client feature. Its version must stay lockstep so the
    # root package can resolve from the registry after publication.
    (
        "crates/running-process/Cargo.toml",
        r'^running-process-protocol\s*=\s*\{[^}]*version\s*=\s*"([^"]+)"',
    ),
    # `uv.lock` records the project's own version for the editable install.
    # It is regenerated by `uv lock`, which is easy to forget because nothing
    # fails without it -- it drifted to 4.6.2 and stayed there across several
    # releases, carrying a stale `ziglang` entry with it long after zig was
    # banned (#792). Checking it here is the only thing that makes the drift
    # visible before a release rather than never.
    (
        "uv.lock",
        r'^name = "running-process"\s+version = "([^"]+)"',
    ),
]


def _extract_version(path: Path, pattern: str) -> str | None:
    text = path.read_text(encoding="utf-8")
    match = re.search(pattern, text, re.MULTILINE)
    return match.group(1) if match else None


def main() -> int:
    # Keyed by (file, pattern), not by file. Several manifests contribute more
    # than one version string -- `crates/running-process/Cargo.toml` alone
    # carries its own `[package] version` plus three sibling pins -- and a
    # file-keyed dict silently kept only the last pattern per file. Four of
    # the checks in SOURCES were never running.
    versions: dict[tuple[str, str], str | None] = {}
    for relpath, pattern in SOURCES:
        versions[(relpath, pattern)] = _extract_version(ROOT / relpath, pattern)

    missing = [key for key, value in versions.items() if value is None]
    if missing:
        for relpath, pattern in missing:
            print(f"ERROR: could not extract version from {relpath} ({pattern})")
        return 1

    unique = set(versions.values())
    if len(unique) != 1:
        print("ERROR: version mismatch across manifests:")
        for (relpath, pattern), ver in versions.items():
            print(f"  {relpath} ({pattern}): {ver}")
        return 1

    print(f"OK: all versions consistent ({unique.pop()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
