#![feature(rustc_private)]

extern crate rustc_ast;
extern crate rustc_errors;
extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_session;

use dylint_linting::dylint_library;
use rustc_ast::LitKind;
use rustc_errors::DiagDecorator;
use rustc_hir::{def::Res, def_id::DefId, Expr, ExprKind};
use rustc_lint::{LateContext, LateLintPass, LintContext};

dylint_library!();

rustc_session::declare_lint! {
    /// ### What it does
    ///
    /// Rejects string literals beginning with `RUNNING_PROCESS_` when they are
    /// passed to the standard environment-variable APIs.
    ///
    /// ### Why is this bad?
    ///
    /// Broker escape hatches and test seams are process-safety boundaries.
    /// Repeating their names as literals makes typoed, stale, or inconsistently
    /// handled controls possible. The production crates define canonical
    /// constants for these names; callers should use those constants.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// let disabled = std::env::var_os("RUNNING_PROCESS_DISABLE").is_some();
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// let disabled = std::env::var_os(RUNNING_PROCESS_DISABLE_ENV).is_some();
    /// ```
    pub RUNNING_PROCESS_ENV_LITERAL,
    Deny,
    "running-process environment controls must use canonical constants"
}

rustc_session::declare_lint! {
    /// ### What it does
    ///
    /// The strict form of `running_process_env_literal` (#1101). In a crate
    /// that opts in, it rejects:
    ///
    /// - **any** string literal passed to `std::env::{var, var_os, set_var,
    ///   remove_var}`, whatever the name; and
    /// - **any** call to those functions from outside a module named `env` or
    ///   `env_vars` -- the declaration tables and the reading mechanism; and
    /// - a string literal passed to `running_process_platform_internal::env::
    ///   {os_named, string_named}`, the reads for a name that is caller data.
    ///
    /// Test builds are exempt as a whole: test code saves and restores the
    /// environment around the variable under test, and every production item
    /// is still linted by the ordinary (non-test) build.
    ///
    /// ### Why is this bad?
    ///
    /// An environment variable is an interface. A read that bypasses the
    /// declaration table is one an embedder cannot find without grepping, and
    /// one whose parser can drift from every other reader of the same kind.
    ///
    /// ### How a crate opts in
    ///
    /// This lint is `allow` by default and switched on per crate, once that
    /// crate is at zero, from its root module:
    ///
    /// ```rust,ignore
    /// #![cfg_attr(dylint_lib = "running_process_env_literal", deny(running_process_env_direct))]
    /// ```
    ///
    /// There is no allowlist: a crate is either at zero and denies it, or it
    /// has not opted in. Each binary is its own crate root and opts in the
    /// same way. A build script is its own crate too and never opts in, so
    /// `build.rs` reads of Cargo's variables (`OUT_DIR`, `CARGO_*`) are not
    /// covered -- and no workspace build script reads the environment today.
    ///
    /// ### Example
    ///
    /// ```rust,ignore
    /// let home = std::env::var_os("HOME");
    /// ```
    ///
    /// Use instead:
    ///
    /// ```rust,ignore
    /// let home = crate::env_vars::HOME.os();
    /// ```
    pub RUNNING_PROCESS_ENV_DIRECT,
    Allow,
    "environment variables must be read through a declared EnvVar"
}

rustc_session::declare_lint_pass!(RunningProcessEnvLiteral => [
    RUNNING_PROCESS_ENV_LITERAL,
    RUNNING_PROCESS_ENV_DIRECT
]);

/// Two lints in one library, so registration is written out rather than
/// generated by `declare_late_lint!`.
#[unsafe(no_mangle)]
pub fn register_lints(sess: &rustc_session::Session, lint_store: &mut rustc_lint::LintStore) {
    dylint_linting::init_config(sess);
    lint_store.register_lints(&[RUNNING_PROCESS_ENV_LITERAL, RUNNING_PROCESS_ENV_DIRECT]);
    lint_store.register_late_pass(|_| Box::new(RunningProcessEnvLiteral));
}

/// The standard functions that read or write one variable by name.
const ENV_FUNCTIONS: &[&str] = &[
    "std::env::var",
    "std::env::var_os",
    "std::env::set_var",
    "std::env::remove_var",
];

/// The mechanism's reads for a name that is caller-supplied data. Calling
/// them is the sanctioned route for such a name, so only rule (a) applies: a
/// literal passed here would be a declared variable in disguise.
const NAMED_FUNCTIONS: &[&str] = &[
    "running_process_platform_internal::env::os_named",
    "running_process_platform_internal::env::string_named",
];

/// Module names that own environment access: the reading mechanism
/// (`running_process_platform_internal::env`) and each crate's declaration
/// table (`env_vars`).
const ENV_MODULES: &[&str] = &["env", "env_vars"];

impl<'tcx> LateLintPass<'tcx> for RunningProcessEnvLiteral {
    fn check_expr(&mut self, cx: &LateContext<'tcx>, expr: &Expr<'tcx>) {
        let ExprKind::Call(callee, arguments) = expr.kind else {
            return;
        };
        let ExprKind::Path(ref qpath) = callee.kind else {
            return;
        };
        let Res::Def(_, def_id) = cx.qpath_res(qpath, callee.hir_id) else {
            return;
        };
        let path = cx.tcx.def_path_str(def_id);
        let named = NAMED_FUNCTIONS.contains(&path.as_str());
        if !named && !ENV_FUNCTIONS.contains(&path.as_str()) {
            return;
        }
        let literal = arguments.first().and_then(|argument| match argument.kind {
            ExprKind::Lit(literal) => match literal.node {
                LitKind::Str(value, _) => Some((argument.span, value)),
                _ => None,
            },
            _ => None,
        });

        if let Some((span, value)) = literal {
            if value.as_str().starts_with("RUNNING_PROCESS_") {
                cx.tcx.dcx().span_err(
                    span,
                    "use the canonical constant for this RUNNING_PROCESS_* environment control",
                );
                return;
            }
        }

        if cx.sess().opts.test {
            return;
        }
        if let Some((span, _)) = literal {
            cx.emit_span_lint(RUNNING_PROCESS_ENV_DIRECT, span, DiagDecorator(|diag| {
                diag.primary_message(
                    "environment variable named by a string literal; declare it and read the declaration",
                );
            }));
            return;
        }
        if named {
            return;
        }
        let module = cx.tcx.parent_module(expr.hir_id).to_def_id();
        if !inside_env_module(cx, module) {
            cx.emit_span_lint(RUNNING_PROCESS_ENV_DIRECT, expr.span, DiagDecorator(|diag| {
                diag.primary_message(
                    "direct environment access outside an `env`/`env_vars` module; read a declared EnvVar instead",
                );
            }));
        }
    }
}

fn inside_env_module(cx: &LateContext<'_>, module: DefId) -> bool {
    cx.tcx.def_path(module).data.iter().any(|segment| {
        segment
            .data
            .get_opt_name()
            .is_some_and(|name| ENV_MODULES.contains(&name.as_str()))
    })
}

#[test]
fn ui() {
    dylint_testing::ui_test(env!("CARGO_PKG_NAME"), "ui");
}
