name: Linux ARM Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: ubuntu-24.04-arm
      artifact-name: wheels-linux-arm
