name: Linux x86 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: ubuntu-24.04
      artifact-name: wheels-linux-x86
