name: macOS x86 Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: macos-15-intel
      artifact-name: wheels-macos-x86
