name: macOS ARM Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: macos-15
      artifact-name: wheels-macos-arm
