name: Windows x86 Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build-mode:
        description: "Build mode"
        required: false
        default: "dev"
        type: choice
        options:
          - dev
          - release

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: windows-2025
      artifact-name: wheels-windows-x86
      build-mode: ${{ inputs.build-mode || 'dev' }}
