name: Windows ARM

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build_dist:
        description: Build and upload distribution artifacts
        required: false
        default: "false"

jobs:
  call:
    uses: ./.github/workflows/_platform-ci.yml
    with:
      runs-on: windows-11-arm
      artifact-name: wheels-windows-arm
      build-dist: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build_dist == 'true' }}
