name: Windows ARM Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: windows-11-arm
      artifact-name: wheels-windows-arm
